from mcp.server.fastmcp import FastMCP
import os
from datetime import datetime

mcp = FastMCP("CodeDoc")

IGNORE_DIRS = {'node_modules', '.git', '__pycache__', 'venv', '.env', 'dist', 'build'}

@mcp.tool()
def generate_smart_doc(code: str, doc_content: str, audit_results: str, code_snippet: str = None, file_path: str = None, language: str = "auto") -> str:
    """
    The universal tool for documentation and audits.
    - If file_path is provided: Reads from local disk.
    - If code_snippet is provided: Documents the pasted code.
    - doc_content & audit_results: Must be generated by the LLM.
    """
    try:
        # 1. Setup target directory
        base_dir = os.path.dirname(os.path.abspath(__file__))
        target_folder = os.path.join(base_dir, "documentation")
        
        # Create folder if it doesn't exist
        os.makedirs(target_folder, exist_ok=True)

        display_name = ""
        final_code = ""

        if file_path:
            
            if not os.path.exists(file_path):
                return f"Error: File '{file_path}' not found."
            with open(file_path, "r", encoding="utf-8") as f:
                final_code = f.read()
            display_name = os.path.basename(file_path)
        elif code_snippet:
            
            final_code = code_snippet
            display_name = "documentation"
        else:
            return "Error: Neither a file path nor a code snippet was provided."

        # 3. Create the output file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{display_name.replace('.', '_')}_{timestamp}.md"
        full_path = os.path.join(target_folder, filename)

        # 4. Build Markdown
        content = f"# Technical Audit & Docs: {display_name}\n"
        content += f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        content += f"## 1. Documentation\n{doc_content}\n\n"
        content += f"## 2. Quality Audit\n{audit_results}\n\n"
        content += f"## 3. Source Code\n```{language}\n{final_code}\n```"

        with open(full_path, "w", encoding="utf-8") as f:
            f.write(content)

        return f"Successfully generated: documentation/{filename}"

    except Exception as e:
        return f"System Error: {str(e)}"

@mcp.tool()
def scan_project_files() -> list:
    """Returns a list of all documentable source files in the current project, ignoring system folders."""
    documentable = []
    for root, dirs, files in os.walk("."):
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        for file in files:
            if file.endswith(('.py', '.js', '.ts', '.java', '.cpp', '.cs')):
                documentable.append(os.path.relpath(os.path.join(root, file)))
    return documentable