from mcp.server.fastmcp import FastMCP
import os
from datetime import datetime

mcp = FastMCP("CodeDoc")

@mcp.tool()
def generate_doc_file(code: str, doc_content: str, language: str = "python") -> str:
    """
    Creates technical documentation. 
    The doc_content should follow this structure: 
    1. Overview, 2. Parameters, 3. Return Values, 4. Validation Logic, 5. Notes.
    """
    try:
        # Determine the directory of the script and point to the /documentation folder
        base_dir = os.path.dirname(os.path.abspath(__file__))
        target_folder = os.path.join(base_dir, "documentation")
        
        if not os.path.exists(target_folder):
            os.makedirs(target_folder)
            
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"doc_{timestamp}.md"
        file_path = os.path.join(target_folder, filename)
        
        # Strictly structured Markdown output
        content = f"# Technical Documentation\n"
        content += f"*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n\n"
        
        content += f"## Source Code Reference\n```{language}\n{code}\n```\n\n"
        
        # This injects the structured content generated by the LLM
        content += f"## Documentation Details\n{doc_content}\n"
        
        content += f"\n---\n*Generated via CodeDoc MCP*"

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
            
        return f"Documentation saved to: documentation/{filename}"
    
    except Exception as e:
        return f"Error: {str(e)}"

if __name__ == "__main__":
    mcp.run()